[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "zisi"
  included_files = ["assets/avian_logo.png"]

[[edge_functions]]
path = "/*"
function = "inject-gmaps-key"
