[build]
  publish = "."
  functions = "netlify/functions"

[[events]]
  type = "submission_created"
  function = "after-submit"

  # netlify.toml
[functions]
  node_bundler = "zisi"
  included_files = ["assets/avian_logo.png"]
